name: "Xcode Install Simulator"
description: "Installs simulator for Xcode developers"
inputs:
  ios_version:
    description: "Version specifier"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: ~/Downloads
        key: ${{ runner.os }}-runtimes-${{ inputs.ios_version }}
    - name: Install Xcodes
      shell: bash
      run: |
        brew tap robotsandpencils/made
        brew install robotsandpencils/made/xcodes
    - name: Install Simulator
      shell: bash
      run: sudo xcodes runtimes install 'iOS ${{ inputs.ios_version }}'
